name: Zoo_Project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  dio: ^5.4.0
  simple_circular_progress_bar: ^1.0.2
  spider: ^4.2.2
  audioplayers: ^5.2.1
  table_calendar: ^3.0.9
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0
  mobile_scanner: ^3.5.6
  
 
  
  
  
  


  





dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  
 

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/svg/
  - assets/image/
  - assets/sound/
  
  


   
  
     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
   - family:  ZooIcons
     fonts:
     - asset: assets/fonts/ZooIcons.ttf
   - family:  museo
     fonts:
     - asset: assets/fonts/museocyrl.ttf
   - family:  Museo700
     fonts:
     - asset: assets/fonts/Museo Cyrl 700.ttf
   - family:  Museo300
     fonts:
     - asset: assets/fonts/Museo Cyrl 300.ttf

       
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
